#!/bin/bash

clear

printf "\033[31;1m"
cat /etc/elsojosmo
printf "\033[0m"

echo "====STATUS=="
git status
echo "============"
echo

git diff

read -p "Is this alright? [Y/n] " ALR

if [ ${ALR:-y} = "n" ] ; then
	echo "Aborting... be safe."
	exit
fi
echo

printf "\033[31;1m"
read -p "Are you feeling dangerous? [y/N] " ISINSANE
printf "\033[0m"

if [ "${ISINSANE:-y}" = "n" ] ; then
	git pull
fi

FUCKO=$(fucko)

git add -A

echo "COMMIT MESSAGE: $FUCKO"

git commit -m "$FUCKO" --quiet

if [ "${ISINSANE:-n}" = "y" ] ; then
	git push -f
else
	git push
fi

