#!/bin/sh

#cp NetworkManager-config/system-connections/* /etc/NetworkManager/system-connections

git pull
git submodule update --init --recursive

mkfifo /etc/wifi-connection

docker compose up --build

