#!/bin/sh

MYTEMPO_DATA=

reset_wifi() {

    nmcli conn down MyTempo
    nmcli conn up MyTempo &
}

while true
do
    read COMMAND < $MYTEMPO_DATA/database/sig-device-operation

    [ "$COMMAND" = "wifi" ] && reset_wifi
done
