#!/bin/sh

set -o xtrace

MYTEMPO_DATA=

reset_wifi() {

    nmcli conn down MyTempo
    sleep 2
    nmcli -w 10 conn up MyTempo
}

reset_lte4g() {

    nmcli conn down chip
    sleep 1
    nmcli -w 10 conn up chip
}

reset_all() {

    reset_lte4g
    reset_wifi
}

while true
do
    read -r COMMAND < "$MYTEMPO_DATA"/database/sig-device-operation

    [ "$COMMAND" = "reset" ] && reset_all
    [ "$COMMAND" = "lte4g" ] && reset_lte4g
    [ "$COMMAND" =  "wifi" ] && reset_wifi
done
